spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tinyfarm}
    username: ${DB_USERNAME:tinyfarm}
    password: ${DB_PASSWORD:tinyfarm}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
